services:
  courses-service:
    image: thiagomag/courses-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mvp-network
    container_name: courses-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: courses_service
      DB_URL_PARAM: ?ssl=false
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

volumes:
  postgres_data:

networks:
  mvp-network:
    external: true